### PR TITLE
Submit yaml file of deployment type.

### PR DESCRIPTION
**Pull request by first-sight12**
>     Delete the specified node name and add node affinity.
>     Modify node affinity.
>     Modify yaml file.
>     Use node affinity instead of specifying the node name.

The PR I submitted just wanted to modify the yaml file of version 1.8

### CODE REVIEW

**Comment by khalid-jobs** [comment]
Thanks for your pr. Would you like to update the other files in the example director? such as https://github.com/kubeedge/edgemesh/blob/main/examples/hostname-lb-default.yaml#L25

**Comment by first-sight12** [comment]
> for your pr. Would you like to update the other files in the example director? such as https://github.com/kubeedge/edgemesh/blob/main/examples/hostname-lb-default.yaml#L25

I'm so sorry. I tested the gateway in the early stage, but it didn't succeed; Others have not been tested, so I can't modify others.

**Pull request merged**
