### PR TITLE
supprot multiply server address

### PR DESCRIPTION
**Pull request by muxuelan**
What type of PR is this?

/kind feature
1、server supports mulitiply  cloud address
2、agent save all server address，when one server is down, the others can work

### CODE REVIEW

**Comment by Poorunga** [comment]
need pass CI

**Comment by khalid-jobs** [comment]
Do you mean support edgemesh-server in HA model or multiple instance model? 
On this issue, the edgemesh-server is stateful, we need to look at the problem of connection, such as agent reconnect.

**Comment by muxuelan** [comment]
hold on/

**Comment by Poorunga** [comment]
edgemesh的高可用方案需要有一个完整的设计

**Pull request closed without merging**
