### PR TITLE
fix markdown images

### PR DESCRIPTION
**Pull request by huapox**
docs/guide/cni.md: fix markdown images

### CODE REVIEW

**Comment by huapox** [comment]
@Poorunga

**Comment by Poorunga** [comment]
@huapox DCO fialed, Please add --sign-off on your commits.

**Comment by huapox** [comment]
> @huapox DCO fialed, Please add `--signoff` on your commits.

@Poorunga resolved

**Comment by huapox** [comment]
@ZBoIsHere @Poorunga  review please

**Pull request merged**
