### PR TITLE
[edgemesh/helm] merge sub charts edgemesh.agent and edgemesh.server  to edgemesh 

### PR DESCRIPTION
**Pull request by zhu733756**
Signed-off-by: zhu733756 <zhu733756@kubesphere.io>

Currently, the sub-charts in edgemesh main chart are independent of each other, this pr aims to merge it.

/cc @Poorunga

### CODE REVIEW

**Comment by Poorunga** [comment]
@zhu733756 CI seems to be a problem, I will reopen your pr and try to re-trigger CI.

/close

**Comment by Poorunga** [comment]
@zhu733756  Please use `helm package` re-create bulid/helm/edgemesh.tgz and build/helm/edgemesh-gateway.tgz

**Comment by zhu733756** [comment]
> @zhu733756 Please use `helm package` re-create bulid/helm/edgemesh.tgz and build/helm/edgemesh-gateway.tgz

Let me see see, maybe we need to build this package automatically.

**Comment by Poorunga** [comment]
> Let me see see, maybe we need to build this package automatically.

Great idea.

**Pull request closed without merging**
