### PR TITLE
add pprof for agent and gateway

### PR DESCRIPTION
**Pull request by JiaweiGithub**
Signed-off-by: jiawei <jiawei.liu@daocloud.io>

**What type of PR is this?**

/kind feature

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by Poorunga** [comment]
@JiaweiGithub Does pprof occupy too many resources during running? Can you make a function that can be switched on and off?

**Comment by JiaweiGithub** [comment]
> @JiaweiGithub Does pprof occupy too many resources during running? Can you make a function that can be switched on and off? example:
> 
> ```
> in edgemesh-agent.yaml:
> 
> 
> commonConfig:
>     pprof: enable
> ```

At present, this function is disabled by default, and it is enabled by the flags parameter.The parameters are profiling-bind-address and profiling-port.
It is also possible to change it to the enable switch of commonConfig, can consider which one is more appropriate.

**Comment by Poorunga** [comment]
> can compare which one is better.

So, what's your advice?

**Comment by JiaweiGithub** [comment]
> > can compare which one is better.
> 
> So, what's your advice?

I prefer the current way, can choose the ip and port to listen to.

**Comment by JiaweiGithub** [comment]
> commonConfig



> > can compare which one is better.
> 
> So, what's your advice?

It will be more convenient to use the config configuration file, I changed the code, please help to review.

**Comment by Poorunga** [comment]
@JiaweiGithub  e2e test is failed

**Comment by JiaweiGithub** [comment]
> @JiaweiGithub e2e test is failed



> @JiaweiGithub e2e test is failed

Fixed

**Pull request merged**
