### PR TITLE
use const instead the string

### PR DESCRIPTION
**Pull request by pengbinbin1**
I think const is better than a string

### CODE REVIEW

**Comment by khalid-jobs** [comment]
Thanks for your pr. And by the way, it seems that you open a new pr for the squash commit or for some other reason.  It is recommended to use the [git rebase](https://blog.csdn.net/itfootball/article/details/44154121)  to squash the commits, and to use `git push -f` to update the pr code. This will keep the records discussed in pr.

**Comment by pengbinbin1** [comment]
> Thanks for your pr. And by the way, it seems that you open a new pr for the squash commit or for some other reason. It is recommended to use the [git rebase](https://blog.csdn.net/itfootball/article/details/44154121) to squash the commits, and to use `git push -f` to update the pr code. This will keep the records discussed in pr.

Thanks for your suggestion, i will try it next time

**Pull request merged**
