### PR TITLE
remove '0.0.0.0' for publicIP 

### PR DESCRIPTION
**Pull request by chenchunxiu**
remove '0.0.0.0' for publicIP

### CODE REVIEW

**Comment by khalid-jobs** [comment]
I think the user's configuration has highest priority. So if user set the `publicIP` empty, he/she needs know what he/she is doing. We can not change the user's configuration, we only can provide them default configuration.

**Comment by chenchunxiu** [comment]
> I think the user's configuration has highest priority. So if user set the `publicIP` empty, he/she needs know what he/she is doing. We can not change the user's configuration, we only can provide them default configuration.

Thanks for your reply. 
publicIP: "" is the default value, some users may not know or forget to modify it.
I am considering that it's better not to let "" overwrite publicIP, because this IP is used for agents to connect.
and, edgemesh-server will collects all server IPs as libp2p addrs, We‘d  better not miss this publicIP

**Comment by khalid-jobs** [comment]
> > I think the user's configuration has highest priority. So if user set the `publicIP` empty, he/she needs know what he/she is doing. We can not change the user's configuration, we only can provide them default configuration.
> 
> Thanks for your reply. publicIP: "" is the default value, some users may not know or forget to modify it. I am considering that it's better not to let "" overwrite publicIP, because this IP is used for agents to connect. and, edgemesh-server will collects all server IPs as libp2p addrs, We‘d better not miss this publicIP

In edgemesh-server, the publicIP's default value is from `util.FetchPublicIP()`, if it is empty,  it will set to `0.0.0.0`

**Comment by chenchunxiu** [comment]
> > > I think the user's configuration has highest priority. So if user set the `publicIP` empty, he/she needs know what he/she is doing. We can not change the user's configuration, we only can provide them default configuration.
> > 
> > 
> > Thanks for your reply. publicIP: "" is the default value, some users may not know or forget to modify it. I am considering that it's better not to let "" overwrite publicIP, because this IP is used for agents to connect. and, edgemesh-server will collects all server IPs as libp2p addrs, We‘d better not miss this publicIP
> 
> In edgemesh-server, the publicIP's default value is not empty. Its default value is from `util.FetchPublicIP()`, if it is empty, it will set to `0.0.0.0`

I mean the default value in edgemesh-server.yaml is empty("").
in addition，I tested it on my machine.
case1: public ip:“” configured in edgemesh-server.yaml    => value is from `util.FetchPublicIP()` will be overrided. 
case2: public ip unconfigured, and fetch publicIP success => value is from `util.FetchPublicIP()` will works
case3: public ip unconfigured, and fetch publicIP success => '0.0.0.0' will be used. By the way,  why we use 0.0.0.0 here ?

**Comment by khalid-jobs** [comment]
It is better to delete the `publicIP: ""` in edgemesh-server.yaml and let the edgemesh-server to fetch the publicIP auto. And if `util.FetchPublicIP()` failed,  users can set it by themself. 
As for the `0.0.0.0`, maybe we can just let it be empty, I think it would be fine.
What do you think?

**Comment by Poorunga** [comment]
> It is better to delete the publicIP: "" in edgemesh-server.yaml

Maybe annotating "publicIP" is a better way to let users know where to fill in this value.

**Comment by khalid-jobs** [comment]
> > It is better to delete the publicIP: "" in edgemesh-server.yaml
> 
> Maybe annotating "publicIP" is a better way to let users know where to fill in this value.

I agree with you

**Comment by chenchunxiu** [comment]
> As for the `0.0.0.0`, maybe we can just let it be empty, I think it would be fine. What do you think?

I agree with you

**Comment by khalid-jobs** [comment]
@chenchunxiu would you mind to update the code according our discussion?

**Comment by chenchunxiu** [comment]
> @chenchunxiu would you mind to update the code according our discussion?

ok. In https://github.com/kubeedge/edgemesh/blob/main/build/server/edgemesh/05-configmap.yaml publicIP is not configured，so that we can ignore publicIP: "".
here I removed the `0.0.0.0` when fetch publicIP failed, pls review again.

**Pull request merged**
