### PR TITLE
[proposal-file] Edgemesh Container Network supports CNI features

### PR DESCRIPTION
**Pull request by IdeaMeshDyx**
**What type of PR is this?**

/kind documentation
 Proposal file pr 

What this PR does / why we need it:
This proposal provides a design for edgemesh to support CNI feature.
There are two main goals:

Implement network partitioning and container IP allocation functions, compatible with CNI standards, and ensure that the IP address of each container in the cluster is unique.
Support cross-subnet Pod IP traffic proxy and forwarding functions, compatible with CNI standards.
Which issue(s) this PR fixes:

Fixes https://github.com/kubeedge/edgemesh/issues/465

### CODE REVIEW

**Comment by Poorunga** [comment]
@IdeaMeshDyx Your file name xxx.md.md have two md. And you can commit two file like: xxx_en.md, xxx_zn.md

**Comment by FengGaoCSC** [comment]
@Poorunga 

On https://github.com/kubeedge/edgemesh/blob/main/docs/proposal/edgemesh-cni-proposal-en.md that you mentioned that 
```
The CNI function of edgemesh is completely independent and needs to verify the node environment during installation. 
If the user has installed other CNIs, the user needs to uninstall or reset the environment. However, edgemesh will be 
compatible with some typical CNI implementations to provide diverse functions, such as Cilium, flannel, calico, kilo, etc.
```

I wonder if the edgemesh CNI could support `Cilium` at the same time or just this edge-mesh cni and cilium cni only one can exist at the same time?

thanks very much

**Comment by Poorunga** [comment]
I think edgemesh-cni should coexist with Cilium. What do you think? @IdeaMeshDyx

**Comment by FengGaoCSC** [comment]
> I think edgemesh-cni should coexist with Cilium. What do you think? @IdeaMeshDyx

Yes, I consider this is the better solutions . When the edgemesh-CNI released officially?

**Comment by fujitatomoya** [comment]
@FengGaoCSC 
CC: @Poorunga @IdeaMeshDyx correct me if i got wrong.

> only cloud side support edgemesh-cni coexist with calico flannel cilium cni

this tries to explain the situation but constraints. i think we can have the bridge at edge if we need to do so just like cloud does here. (i do not really understand the diagram in Chinese, just guessing)

> edge side will using edgemesh cni only

this is one of the requirement that it needs to use edgemesh CNI if they want to have cloud-edge or cross-edge communication in edgemesh perspective.

> And when the edgemesh-CNI released officially?

good question but hard to answer... please understand this is no pressure, we understand this is open source development.

**Pull request merged**
